image: node:6

stages:
  - test
  - build
  - deploy
cache:
  paths:
    - node_modules/

test:
  stage: test
  before_script:
    - npm install
  script:
    - npm test

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm run generate

deploy:
  stage: deploy
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase deploy -m "Deploy $CI_PROJECT_PATH by pipeline $CI_PIPELINE_ID in job $CI_JOB_ID" --non-interactive --token $FIREBASE_TOKEN
